# Generated by Django 3.2.9 on 2021-12-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'streets',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('street_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simple_app.streets')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
    ]
